fix(versal2): remove extraneous parentheses
While compiling TF-A with Armclang, the following error was observed.
To fix it, the extraneous parentheses around the comparison were
removed to silence the warning.

plat/amd/versal2/scmi.c:322:13: error: equality comparison with
extraneous parentheses [-Werror,-Wparentheses-equality]
        if ((clock == NULL)) {

Change-Id: I51f955dd15d5020598c9e4ff2f7f92b55a909f9b
Signed-off-by: Prasad Kummari <prasad.kummari@amd.com>
State: upstream (bb2b0227c6b9996d9bc5a91cec5cc0a4a40c3e2c)